//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by f:\Programmering\C++\fuldc\branches\6.65-maintenance\DCPlusPlus.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_SLOTSPIN                    101
#define IDC_TRAY_QUIT                   102
#define IDC_TRAY_SHOW                   103
#define IDC_COPY_HUB                    104
#define IDC_COPY_FILENAME               105
#define IDC_COPY_PATH                   106
#define IDD_GENERALPAGE                 107
#define IDC_COPY_SIZE                   107
#define IDC_SET_PRIORITY                108
#define ID_VIEW_TRANSFER_VIEW           108
#define IDC_NOTIFY                      109
#define IDC_OPEN                        110
#define IDC_PM_UP                       111
#define IDC_PM_DOWN                     112
#define IDC_SHOWLOG                     113
#define IDC_HUBISP                      114
#define IDC_HELP_FULPAGE                114
#define IDC_HUBUSERISP                  115
#define IDC_CLOSE_ALL_PM                115
#define IDC_DELETE                      116
#define IDC_CLOSE_ALL_DIR_LIST          116
#define IDC_COPY_TTH                    117
#define IDC_TTH                         118
#define IDC_SHOW_HUB_LOG                119
#define IDC_OPEN_LOG_DIR                120
#define IDC_OPEN_MY_LIST                121
#define IDC_HEADER_MENU                 122
#define IDC_SEARCH_BY_TTH               123
#define IDC_RESOLVE_IP                  125
#define IDC_RESOLVED_IP                 126
#define IDC_SEARCH_RELEASEALTERNATES    127
#define IDC_SETTINGS_GET_USER_COUNTRY   127
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDC_TOOLBAR                     129
#define IDC_PUBLIST                     130
#define IDC_HUBLIST                     131
#define IDR_MDIDIRECTORY                132
#define IDC_SERVER                      133
#define IDC_CLOSE_ALL_SEARCH_FRAME      133
#define IDD_HUBS                        134
#define IDC_FILES                       135
#define IDC_PASTE                       135
#define IDC_PRIORITY                    136
#define IDC_CHATCOMMANDS                136
#define IDC_ITEMS                       137
#define IDC_BOLD                        138
#define IDC_ITALIC                      139
#define IDC_UNDERLINE                   140
#define IDC_STRIKEOUT                   141
#define IDC_INCLUDENICK                 142
#define IDC_WHOLELINE                   143
#define IDC_CASESENSITIVE               144
#define IDC_BGCOLOR                     145
#define IDC_FGCOLOR                     146
#define IDC_MATCHTYPE                   147
#define IDC_STRING                      148
#define IDC_UPDATE                      149
#define IDC_COPY                        150
#define IDC_REFRESH_MENU                151
#define IDC_SETTINGS_LOG_STATUS_MESSAGES 152
#define IDC_SETTINGS_ONLY_HASHED        153
#define IDC_HASH_PROGRESS               154
#define IDR_DIRECTORY                   155
#define IDR_FINISHED_DL                 156
#define IDR_FINISHED_UL                 157
#define IDR_HUB                         158
#define IDR_NET_STATS                   159
#define IDR_PRIVATE                     160
#define IDR_QUEUE                       161
#define IDR_SEARCH                      162
#define IDR_SPY                         163
#define IDR_USERS                       164
#define IDC_CURRENT_FILE                165
#define IDC_HASH_SPEED                  166
#define IDC_FILES_PER_HOUR              167
#define IDC_TIME_LEFT                   168
#define IDC_STATISTICS                  169
#define IDC_HASH_INDEXING               170
#define IDD_SETTINGS                    201
#define IDD_HASH_PROGRESS               202
#define IDD_PASSWORD                    209
#define IDD_LINE                        209
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_UPLOADPAGE                  212
#define IDD_APPEARANCEPAGE              213
#define IDR_PUBLICHUBS                  215
#define IDR_FAVORITES                   217
#define IDD_FAVORITEHUB                 223
#define IDD_LOGPAGE                     224
#define IDD_USER_COMMAND                230
#define IDR_ADLSEARCH                   233
#define IDD_ADLS_PROPERTIES             234
#define IDD_UCPAGE                      236
#define IDD_FULPAGE                     238
#define IDD_FULSHAREPAGE                238
#define IDD_PRIORITY                    239
#define IDD_HIGHLIGHTPAGE               240
#define IDC_SEARCH                      241
#define IDD_FULADVANCEDPAGE             242
#define IDD_WEB_SHORTCUTS               243
#define IDR_HUBFRAME                    247
#define IDD_DIALOG1                     248
#define IDD_FULPAGE2                    248
#define IDD_FULDOWNLOADPAGE             248
#define IDR_PRIVATEFRAME                249
#define IDC_SETTINGS_MAX_HASH_SPEED     250
#define IDC_MAX_HASH_SPEED              251
#define IDC_SETTINGS_MBS                252
#define IDD_FULAPPEARANCEPAGE           253
#define IDR_NOTEPAD                     256
#define IDD_DIALOG2                     257
#define IDD_FULTABSPAGE                 257
#define IDD_DIALOG3                     258
#define IDD_FULPOPUPPAGE                258
#define IDC_ADLSP_SEARCH                259
#define IDC_ADLSP_TYPE                  260
#define IDC_ADLSP_SIZE_MIN              261
#define IDC_ADLSP_SIZE_MAX              262
#define IDC_ADLSP_UNITS                 263
#define IDC_ADLSP_DESTINATION           264
#define IDC_FH_HUB                      265
#define IDC_FH_IDENT                    266
#define IDC_FH_NAME                     267
#define IDC_FH_ADDRESS                  268
#define IDC_FH_HUB_DESC                 269
#define IDC_FH_NICK                     270
#define IDC_FH_PASSWORD                 271
#define IDC_FH_USER_DESC                272
#define IDC_USER_CMD_PREVIEW            273
#define IDC_USER_CMD_OPEN_HELP          274
#define IDC_PUB_LIST_CONFIG             275
#define IDC_PUB_LIST_DROPDOWN           276
#define IDC_SETTINGS_LIST_CONFIG        277
#define IDD_HUB_LIST                    278
#define IDC_LIST_ADD                    279
#define IDC_LIST_DESC                   280
#define IDC_LIST_DOWN                   281
#define IDC_LIST_EDIT                   282
#define IDC_LIST_LIST                   283
#define IDC_LIST_REMOVE                 284
#define IDC_LIST_UP                     285
#define IDC_LIST_EDIT_BOX               286
#define IDC_OPEN_OWN_LIST               287
#define IDC_SETTINGS_UDP_PORT           289
#define IDC_UDP_PORT                    290
#define IDD_APPEARANCE2PAGE             291
#define IDC_SETTINGS_FILE_NAME1         292
#define IDC_SETTINGS_FILE_NAME          292
#define IDC_SETTINGS_FILE_NAME2         293
#define IDC_SETTINGS_FILE_NAME3         294
#define IDC_SETTINGS_FILE_NAME4         295
#define IDC_UPLOAD_FILE                 296
#define IDC_PRIVATE_CHAT_FILE           297
#define IDC_ONLYTTH                     298
#define IDC_MAIN_CHAT_FILE              299
#define IDC_LOG_FILE                    299
#define IDC_LOG_STATUS_MESSAGES         300
#define IDC_DOWNLOAD_FILE               301
#define IDD_ADVANCED3PAGE               302
#define IDC_SETTINGS_TIME_STAMPS_FORMAT 303
#define IDC_TIME_STAMPS_FORMAT          304
#define IDC_SETTINGS_FILELIST_MENU      305
#define IDD_NETWORKPAGE                 306
#define IDC_SETTINGS_PM_HISTORY         307
#define IDC_SHOW_LAST_LINES_LOG         309
#define IDD_FULIGNOREPAGE               309
#define IDD_DIALOG4                     310
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_HELP_CONTENTS               1004
#define IDC_CONNECTION                  1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1006
#define IDC_PASSIVE                     1007
#define IDC_PORT                        1008
#define IDC_DIRECTORIES                 1009
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_RENAME                      1013
#define IDC_TOTAL                       1014
#define IDC_SLOTS                       1015
#define IDC_TRANSFERS                   1017
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1018
#define IDC_RESULTS                     1019
#define IDC_PASSWORD                    1019
#define IDC_LINE                        1019
#define IDC_DOWNLOADDIRTO               1020
#define IDC_PRIVATEMESSAGE              1021
#define IDC_VERSION                     1021
#define IDC_GETLIST                     1022
#define IDC_ROLLBACK                    1022
#define IDC_KICK                        1023
#define IDC_REDIRECT                    1024
#define IDC_AUTOFOLLOW                  1024
#define IDC_REMOVESOURCE                1025
#define IDC_EDIT                        1026
#define IDC_NOTEPAD                     1027
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_SELWINCOLOR                 1031
#define IDC_SELTEXTCOLOR                1032
#define IDC_SELTEXT                     1032
#define IDC_COLOREXAMPLE                1033
#define IDC_SELFONT                     1034
#define IDC_SHAREHIDDEN                 1035
#define IDC_REMOVEFINISHED              1036
#define IDC_QUEUE                       1037
#define IDC_FILTERKICK                  1037
#define IDC_MINIMIZETRAY                1038
#define IDC_OPENPUBLIC                  1039
#define IDC_OPENQUEUE                   1040
#define IDC_HUBNICK                     1041
#define IDC_HUBPASS                     1042
#define IDC_NEWFAV                      1042
#define IDC_HUBNAME                     1043
#define IDC_SOURCE_TYPE                 1044
#define IDC_AUTOSEARCH                  1045
#define IDC_SIZE_TYPE                   1045
#define IDC_TIMESTAMPS                  1046
#define IDC_HUBDESCR                    1047
#define IDC_CONFIRMEXIT                 1047
#define IDC_HUBADDR                     1048
#define IDC_IGNOREOFFLINE               1048
#define IDC_GRANTSLOT                   1049
#define IDC_POPUPOFFLINE                1049
#define IDC_FORCE                       1050
#define IDC_BUFFERSIZE                  1051
#define IDC_LANGUAGE                    1052
#define IDC_BROWSE                      1053
#define IDC_PUBLIC_HUBS                 1054
#define IDC_THANKS                      1055
#define IDC_DOWNLOADS                   1056
#define IDC_FULTHANKS                   1056
#define IDC_SLOTSSPIN                   1057
#define IDC_MAXSPEED                    1058
#define IDC_SPEEDSPIN                   1059
#define IDC_FAVUSERS                    1060
#define IDC_PROXY                       1060
#define IDC_ADD_TO_FAVORITES            1061
#define IDC_LOG_MAIN_CHAT               1061
#define IDC_LOG_PRIVATE_CHAT            1062
#define IDC_HELP_HOMEPAGE               1063
#define IDC_LOG_DOWNLOADS               1063
#define IDC_HELP_DOWNLOADS              1064
#define IDC_LOG_UPLOADS                 1064
#define IDC_HELP_REPORT_BUG             1065
#define IDC_LOG_DIRECTORY               1065
#define IDC_HELP_REQUEST_FEATURE        1066
#define IDC_BROWSE_LOG                  1066
#define IDC_HELP_DISCUSS                1067
#define IDC_HELP_HELP_FORUM             1068
#define IDC_HELP_FAQ                    1069
#define IDC_SEARCH_SPY                  1070
#define IDC_LATEST                      1071
#define IDC_PRIVATE_MESSAGE_BEEP        1072
#define IDC_USE_SYSTEM_ICONS            1072
#define IDC_UPTIME                      1072
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1073
#define IDC_POPUP_PMS                   1073
#define IDC_USE_OEM_MONOFONT            1073
#define IDC_STATUS_IN_CHAT              1074
#define IDC_MIN_UPLOAD_SPEED            1074
#define IDC_SETTINGS_TYPE               1074
#define IDC_SHOW_JOINS                  1075
#define IDC_MIN_UPLOAD_SPIN             1075
#define IDC_CHEVRON                     1076
#define IDC_URL_HANDLER                 1076
#define IDC_SOUND                       1076
#define IDC_OPEN_FILE_LIST              1077
#define IDC_TOTALS                      1077
#define IDC_RATIO                       1078
#define IDC_HELP_README                 1079
#define IDC_POST_DOWNLOAD               1079
#define IDC_CLOSE_WINDOW                1080
#define IDC_POST_UPLOAD                 1080
#define IDC_FIND                        1081
#define IDC_MAIN_CHAT                   1081
#define IDC_LOG_FORMAT                  1081
#define IDC_NEXT                        1082
#define IDC_PRIVATE_CHAT                1083
#define IDC_FINISHED                    1084
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1084
#define IDC_BROWSETEMPDIR               1085
#define IDC_AUTO_AWAY                   1086
#define IDC_SOCKS_RESOLVE               1086
#define IDC_REMOVEALL                   1087
#define IDC_SMALL_SEND_SIZE             1087
#define IDC_SMALL_SEND_BUFFER           1087
#define IDC_HELP_DONATE                 1088
#define IDC_SOCKS5                      1089
#define IDC_SOCKS_SERVER                1090
#define IDC_SOCKS_PORT                  1091
#define IDC_SOCKS_USER                  1092
#define IDC_SOCKS_PASSWORD              1093
#define IDC_FREESLOTS                   1094
#define IDC_KEEP_LISTS                  1094
#define IDC_AUTO_KICK                   1095
#define IDC_HELP_TRANSLATIONS           1095
#define IDC_COPY_NICK                   1096
#define IDC_ADVANCED_BOOLEANS           1096
#define IDC_ADD_MENU                    1097
#define IDC_MOVE                        1098
#define IDC_REMOVE_MENU                 1098
#define IDC_MENU_ITEMS                  1099
#define IDC_CHANGE_MENU                 1100
#define IDC_NAME                        1101
#define IDC_COMMAND                     1102
#define IDC_HUB                         1103
#define IDC_COMMAND_DESCRIPTION         1105
#define IDC_APPEARANCE_BOOLEANS         1106
#define IDC_DEFAULT_AWAY_MESSAGE        1107
#define IDC_MAX_TAB_ROWS                1107
#define IDC_CLOSE_DISCONNECTED          1108
#define IDC_OPEN_FOLDER                 1109
#define IDC_OPEN_FILE                   1110
#define IDC_FILE_ADL_SEARCH             1111
#define IDC_ADLLIST                     1113
#define IDC_MOVE_UP                     1114
#define IDC_MOVE_DOWN                   1115
#define IDC_HUBUSERDESCR                1116
#define IDC_FINISHED_UL                 1117
#define IDC_SEARCH_STRING               1118
#define IDC_DEST_DIR                    1119
#define IDC_IS_ACTIVE                   1120
#define IDC_MIN_FILE_SIZE               1121
#define IDC_MAX_FILE_SIZE               1122
#define IDC_AUTOQUEUE                   1123
#define IDC_GO_TO_DIRECTORY             1124
#define IDC_MATCH_QUEUE                 1125
#define IDC_HELP_CHANGELOG              1126
#define IDC_VIEW_AS_TEXT                1129
#define IDC_PAGE                        1130
#define IDC_NET_STATS                   1131
#define IDC_SETTINGS_PERSONAL_INFORMATION 1132
#define IDC_SETTINGS_NICK               1133
#define IDC_SETTINGS_EMAIL              1134
#define IDC_SETTINGS_DESCRIPTION        1135
#define IDC_SETTINGS_CONNECTION_TYPE    1136
#define IDC_SETTINGS_CONNECTION_SETTINGS 1137
#define IDC_SETTINGS_IP                 1138
#define IDC_SETTINGS_PORT               1139
#define IDC_SETTINGS_SOCKS5_IP          1140
#define IDC_SETTINGS_SOCKS5_PORT        1141
#define IDC_SETTINGS_SOCKS5_USERNAME    1142
#define IDC_SETTINGS_SOCKS5_PASSWORD    1143
#define IDC_SETTINGS_DIRECTORIES        1144
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1145
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1146
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1147
#define IDC_SETTINGS_DOWNLOADS_MAX      1148
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1149
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1150
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1151
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1152
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1153
#define IDC_SETTINGS_SHARED_DIRECTORIES 1154
#define IDC_SETTINGS_SHARE_SIZE         1155
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1156
#define IDC_SETTINGS_UPLOADS_SLOTS      1157
#define IDC_SETTINGS_COLORS             1158
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1159
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1160
#define IDC_SETTINGS_LANGUAGE_FILE      1161
#define IDC_SETTINGS_REQUIRES_RESTART   1162
#define IDC_SETTINGS_LOGGING            1163
#define IDC_SETTINGS_LOG_DIR            1164
#define IDC_SETTINGS_SOUNDS             1165
#define IDC_SETTINGS_ADVANCED           1166
#define IDC_SETTINGS_ROLLBACK           1167
#define IDC_SETTINGS_CLIENT_VER         1168
#define IDC_SETTINGS_WRITE_BUFFER       1169
#define IDC_SETTINGS_MAX_TAB_ROWS       1170
#define IDC_SETTINGS_USER_MENU          1171
#define IDC_SETTINGS_KB                 1172
#define IDC_SETTINGS_B                  1173
#define IDC_SETTINGS_KBPS               1174
#define IDC_ADD_AS_FAVORITE             1175
#define IDC_SETTINGS_SEPARATOR          1194
#define IDC_SETTINGS_RAW                1195
#define IDC_SETTINGS_CHAT               1196
#define IDC_SETTINGS_PM                 1197
#define IDC_SETTINGS_HUB_MENU           1198
#define IDC_SETTINGS_SEARCH_MENU        1200
#define IDC_SETTINGS_CONTEXT            1201
#define IDC_SETTINGS_PARAMETERS         1202
#define IDC_SETTINGS_NAME               1203
#define IDC_SETTINGS_COMMAND            1204
#define IDC_SETTINGS_HUB                1205
#define IDC_SETTINGS_TO                 1206
#define IDC_FINAL_TEXT                  1207
#define IDC_RESULT                      1207
#define IDC_WEB_SHORTCUTS_ADD           1208
#define IDC_COLOR_BUTTON                1208
#define IDC_SELECT_SOUND                1208
#define IDC_BTN_COLOR                   1208
#define IDC_WEB_SHORTCUTS_REMOVE        1209
#define IDC_TEXTCOLOR                   1209
#define IDC_MOVEUP                      1209
#define IDC_BTN_TEXTCOLOR               1209
#define IDC_REFRESH_FILE_LIST           1210
#define IDC_WEB_SHORTCUTS_PROPERTIES    1210
#define IDC_SELECT_SOUND2               1210
#define IDC_PRESET                      1210
#define IDC_ONCE_PER_NICK               1211
#define IDC_SETTINGS_ONCE               1212
#define IDC_OPEN_DOWNLOADS              1213
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1214
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1215
#define IDC_SKIPLIST                    1217
#define IDC_SKIPLIST_DOWNLOAD           1218
#define IDC_REFRESH_TIME                1219
#define IDC_INCOMING_REFRESH_TIME       1220
#define IDC_SKIPLIST_SHARE              1221
#define IDC_SHARE_REFRESH_TIME          1222
#define IDC_CHATBUFFERSIZE              1223
#define IDC_WHOLE                       1224
#define IDC_WHOLEWORD                   1225
#define IDC_UL_BG                       1226
#define IDC_COLOR                       1227
#define IDC_COLOR_SELECTION             1228
#define IDC_STRIPISP                    1229
#define IDC_POPUP                       1229
#define IDC_REFRESH_INCOMING            1229
#define IDC_CLEAN                       1229
#define IDC_WEB_SHORTCUTS_CLEAN         1229
#define IDC_MESSAGE                     1230
#define IDC_REFRESH_SHARE               1230
#define IDC_LOGMAINCHAT                 1230
#define IDC_DISPLAYTIME                 1231
#define IDC_ONLY_REFRESH_INCOMING       1231
#define IDC_ONLY_REFRESH_SHARE          1232
#define IDC_FUL_ADVANCED_BOOLEANS       1234
#define IDC_WEB_SHORTCUT_NAME           1235
#define IDC_WEB_SHORTCUT_KEY            1236
#define IDC_WEB_SHORTCUT_URL            1237
#define IDC_WEB_SHORTCUTS_DESC          1238
#define IDC_WEB_SHORTCUT_URL_DESC       1239
#define IDC_WEB_SHORTCUTS_HOWTO         1240
#define IDC_WEB_SHORTCUTS_NAME_DESC     1241
#define IDC_WEB_SHORTCUT_KEY_DESC       1242
#define IDC_WEB_SHORTCUTS_LIST          1242
#define IDC_COLOR_COMBO                 1243
#define IDC_TABCOLOR                    1245
#define IDC_FONT                        1246
#define IDC_TABCOLOR2                   1246
#define IDC_LASTLOG                     1246
#define IDC_BTN_FONT                    1246
#define IDC_FREE_SLOTS_EXTENSIONS       1247
#define IDC_MINISLOTS_EXTENSIONS        1247
#define IDC_FLASHWINDOW                 1247
#define IDC_FREE_SLOTS_SIZE             1249
#define IDC_MINISLOTS_SIZE              1249
#define IDC_HAS_BG_COLOR                1250
#define IDC_MOVEDOWN                    1251
#define IDC_HAS_FG_COLOR                1252
#define IDC_PATHS                       1253
#define IDC_TAB_SIZE                    1254
#define IDC_SETTINGS_FORMAT1            1255
#define IDC_MAX_SOURCES                 1255
#define IDC_SETTINGS_FORMAT             1255
#define IDC_SETTINGS_FORMAT2            1256
#define IDC_SETTINGS_FORMAT3            1257
#define IDC_SETTINGS_FORMAT4            1258
#define IDC_SETTINGS_LOG_SYSTEM         1259
#define IDC_LOG_SYSTEM                  1260
#define IDC_MESSAGE_LENGTH              1262
#define IDC_SB_SKIPLIST_DOWNLOAD        1263
#define IDC_ST_SKIPLIST_DOWNLOAD        1264
#define IDC_ST_SKIPLIST                 1264
#define IDC_SB_SKIPLIST_SHARE           1265
#define IDC_ST_SKIPLIST_SHARE           1266
#define IDC_SB_REFRESH                  1267
#define IDC_ST_REFRESH_INCOMING         1268
#define IDC_ST_REFRESH_SHARE            1269
#define IDC_ST_REFRESH_HELP             1270
#define IDC_SB_CHATBUFFERSIZE           1271
#define IDC_ST_CHATBUFFERSIZE           1272
#define IDC_SB_TAB_COLORS               1273
#define IDC_SB_TAB_SIZE                 1274
#define IDC_SB_POPUP                    1275
#define IDC_ST_DISPLAYTIME              1276
#define IDC_ST_MESSAGE_LENGTH           1277
#define IDC_SB_MINISLOTS                1278
#define IDC_SB_TIME_STAMPS              1278
#define IDC_ST_MINISLOTS_EXT            1279
#define IDC_ST_MINISLOTS_SIZE           1280
#define IDC_SB_PATHS                    1281
#define IDC_ST_PATHS                    1282
#define IDC_SB_MAX_SOURCES              1283
#define IDC_SB_WEB_SHORTCUTS            1284
#define IDC_SB_HIGHLIGHT                1285
#define IDC_SB_SETTINGS                 1286
#define IDC_ST_MATCH_TYPE               1287
#define IDC_EDIT_TIME_STAMPS            1288
#define IDC_BTN_TIME_STAMP_HELP         1289
#define IDC_DOWNLOAD_LIST               1290
#define IDC_TAB_DIRTY_BLEND             1292
#define IDC_SB_                         1293
#define IDC_SB_TAB_DIRTY_BLEND          1293
#define IDC_CH_STATUS_HUB_BOLD          1294
#define IDC_CH_STATUS_PM_BOLD           1295
#define IDC_POPUP_AWAY                  1295
#define IDC_CH_ICONS                    1296
#define IDC_POPUP_MINIMIZED             1296
#define IDC_CH_BLEND                    1297
#define IDC_POPUP_ON_PM                 1297
#define IDC_POPUP_ON_NEW_PM             1298
#define IDC_POPUP_ON_HUBSTATUS          1299
#define IDC_POPUP_REMOVE                1300
#define IDC_APPEARANCE                  1301
#define IDC_POPUP_APPEARANCE            1301
#define IDC_                            1302
#define IDC_STRIP_ISP                   1302
#define IDC_POPUP_ACTIVATE_ON_CLICK     1302
#define IDC_FH_STRIP_ISP                1303
#define IDC_POPUP_REMOVE3               1303
#define IDC_POPUP_DONT_SHOW_ACTIVE      1303
#define IDC_FH_LOG_MAIN_CHAT            1304
#define IDC_DUPES                       1304
#define IDC_BUTTON1                     1305
#define IDC_DUPE_COLOR                  1305
#define IDC_NOTTH_BOX                   1306
#define IDC_DUPE_COLOR2                 1307
#define IDC_NOTTH                       1307
#define IDC_LOG_OPTIONS                 1308
#define IDC_IGNORE                      1309
#define IDC_UNIGNORE                    1310
#define IDC_PATTERNS                    1311
#define IDC_REMOVE_FILE                 1312
#define IDC_SEARCH_HISTORY              1313
#define IDC_SETTINGS_SEARCH_HISTORY     1314
#define IDC_SEARCH_HISTORY_SPIN         1315
#define IDC_PRESETMENU                  1316
#define IDC_DUPE_DESCRIPTION            1317
#define IDC_NOTTH_DESCRIPTION           1318
#define IDC_ONLY_REFRESH_INCOMING_TIME1 1319
#define IDC_ONLY_REFRESH_INCOMING_TIME2 1320
#define IDC_ONLY_REFRESH_SHARE_TIME1    1321
#define IDC_ONLY_REFRESH_SHARE_TIME2    1322
#define IDC_BIND_ADDRESS                1323
#define IDC_SETTINGS_BIND_ADDRESS       1324
#define IDC_WINDOWS_STARTUP             1325
#define IDC_IPADDRESS1                  1325
#define IDC_SETTINGS_AUTO_OPEN          1326
#define IDC_LIST1                       1326
#define IDC_POPUP_ITEMS                 1326
#define IDC_SETTINGS_WINDOWS_OPTIONS    1327
#define IDC_HISTORY                     1327
#define IDC_WINDOWS_OPTIONS             1328
#define IDD_WINDOWSPAGE                 1329
#define IDC_BUTTON3                     1329
#define IDC_FILTER_HISTORY              1329
#define IDC_SET_MINISLOT_SIZE           1330
#define IDC_SETTINGS_TEXT_MINISLOT      1331
#define IDC_SETTINGS_KB2                1332
#define IDC_BROWSELIST                  3000
#define IDC_REMOVE_SOURCE               3500
#define IDC_PM                          4000
#define IDC_READD                       4500
#define IDC_DOWNLOAD_TARGET             5000
#define IDC_DOWNLOAD_TARGET_DIR         5500
#define IDC_SELECT_WINDOW               6000
#define IDC_USER_COMMAND                6500
#define IDC_PRIORITY_PAUSED             7000
#define IDC_PRIORITY_LOWEST             7001
#define IDC_PRIORITY_LOW                7002
#define IDC_PRIORITY_NORMAL             7003
#define IDC_PRIORITY_HIGH               7004
#define IDC_PRIORITY_HIGHEST            7005
#define IDC_DOWNLOAD_WHOLE_TARGET       7500
#define IDC_REMOVE_SOURCES              8000
#define IDC_REMOVE_SOURCE_ALL           8500
#define IDC_READD_QUEUE                 9000
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define ID_FILE_QUICK_CONNECT           32777
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define IDC_SEND_MESSAGE                32786
#define IDC_FILTER_FOCUS                32788
#define ID_VIEW_STATUSBAR               32789
#define IDC_SWITCH_WINDOW_1             32798
#define IDC_SWITCH_WINDOW_2             32799
#define IDC_SWITCH_WINDOW_3             32800
#define IDC_SWITCH_WINDOW_4             32801
#define IDC_SWITCH_WINDOW_5             32802
#define IDC_SWITCH_WINDOW_6             32803
#define IDC_SWITCH_WINDOW_7             32804
#define IDC_SWITCH_WINDOW_8             32805
#define IDC_SWITCH_WINDOW_9             32806
#define IDC_SWITCH_WINDOW_0             32807
#define ID_WINDOW_MINIMIZE_ALL          57654
#define ID_WINDOW_RESTORE_ALL           57655

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1329
#define _APS_NEXT_SYMED_VALUE           137
#endif
#endif
